export const cmsEndpoints = {
    userAvatars: {
        list: 'settings/user-avatars/',
        create: 'settings/user-avatars/',
        deleteCurrent: 'settings/user-avatars/current/',
    },
    auth: {
        login: 'cms/adp/authorization/',
        validateRegistration: 'cms/adp/validate-registration/',
        sendCode: 'cms/adp/send-code/',
        verifyCode: 'cms/adp/verify-code/',
        resetPassword: 'cms/adp/reset-password/',
        registration: 'cms/adp/registration/',
        registrationSettings: 'cms/adp/registration-settings/',
        passwordResetSettings: 'cms/adp/password-reset-settings/',
        profileSettings: 'cms/adp/profile-settings/',
        profileChangeRequests: 'cms/adp/profile-change-requests/',
        validateInvitation: 'cms/adp/invitations/validate/',
        protected: 'cms/adp/protected/',
        sessionBootstrap: 'cms/adp/session-bootstrap/',
        changePassword: 'cms/adp/change-password/',
        devices: 'cms/adp/devices/',
        deleteDevice: id => `cms/adp/devices/${id}/`,
        profile: 'cms/adp/profile/',
        menu: 'cms/adp/user-menu-data/',
        securitySettings: 'cms/adp/security-settings/',
    },
    cms: {
        disabledModules: 'cms/disabled-modules/',
        checkAccessToAdminPanel: 'cms/check_access_to_admin_panel/',

        getpages: 'cms/get-cms-pages',

        roles: {
            list: 'cms/adp/roles/',
            detail: 'cms/adp/roles/',
        },
        roleGroups: {
            list: 'cms/adp/role-groups/',
            detail: 'cms/adp/role-groups/',
        },
        policies: {
            list: 'cms/adp/policies/',
            detail: 'cms/adp/policies/',
        },
        modulePermissions: 'cms/adp/module-permissions/',
        moduleCatalog: 'cms/adp/module-catalog/',
        assignRole: 'cms/adp/assign-role/',
        adminUsers: 'cms/adp/admin-users/',
        adminUserDetail: (userId) => `cms/adp/admin-users/${userId}/`,
        adminUserAvatar: (userId) => `cms/adp/admin-users/${userId}/avatar/`,
        adminUserResetPassword: (userId) => `cms/adp/admin-users/${userId}/reset-password/`,
        presence: {
            batch: 'cms/adp/presence/',
            heartbeat: 'cms/adp/presence/heartbeat/',
            offline: 'cms/adp/presence/offline/',
            adminSnapshot: 'cms/adp/presence/admin-snapshot/',
        },
        importUsers: 'cms/adp/import-users/',
        importUsersWelcomeEmailDefaults: 'cms/adp/import-users/welcome-email-defaults/',
        importUsersTaskStatus: (taskId) => `cms/adp/import-users/status/${taskId}/`,
        importUsersPasswords: (taskId) => `cms/adp/import-users/passwords/${taskId}/`,
        invitations: 'cms/adp/invitations/',
        invitationsBulk: 'cms/adp/invitations/bulk/',
        invitationsBulkSend: 'cms/adp/invitations/bulk/send/',
        invitationsClear: 'cms/adp/invitations/clear/',
        invitationDetail: (id) => `cms/adp/invitations/${id}/`,
        invitationResend: (id) => `cms/adp/invitations/${id}/resend/`,
        profileChangeRequestsAdmin: 'cms/adp/profile-change-requests/admin/',
        profileChangeRequestApprove: (id) => `cms/adp/profile-change-requests/${id}/approve/`,
        profileChangeRequestReject: (id) => `cms/adp/profile-change-requests/${id}/reject/`,
        myPermissions: 'cms/adp/my-permissions/',
        checkURLAccess: 'cms/adp/check-url-access/',

        menu: {
            userMenu: 'cms/adp/menu/',
            items: 'cms/adp/menu/items/',
            itemDetail: (id) => `cms/adp/menu/items/${id}/`,
            reorder: 'cms/adp/menu/items/reorder/',
            separators: 'cms/adp/menu/separators/',
            separatorDetail: (id) => `cms/adp/menu/separators/${id}/`,
            accessLog: 'cms/adp/menu/access-log/',
            availableIcons: 'cms/adp/menu/available-icons/',
            restore: 'cms/adp/menu/restore/',
        },
    },
    themes: {
        list: 'settings/themes/',
        detail: (id) => `settings/themes/${id}/`,
        create: 'settings/themes/',
        update: (id) => `settings/themes/${id}/`,
        delete: (id) => `settings/themes/${id}/`,
        active: 'settings/themes/active/',
        activate: (id) => `settings/themes/${id}/activate/`,
        duplicate: (id) => `settings/themes/${id}/duplicate/`,
        export: (id) => `settings/themes/${id}/export/`,
        resetDefaults: (id) => `settings/themes/${id}/reset-defaults/`,
        import: 'settings/themes/import/',
        createSystemThemes: 'settings/themes/create-system-themes/',
    },
};
