/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const logError: typeof import('@/js/utils/logError.js').logError
  const logWarn: typeof import('@/js/utils/logError.js').logWarn
  const sanitizeError: typeof import('@/js/utils/logError.js').sanitizeError
}
